#!/usr/bin/env bash
xrdb -merge ~/.Xresources
# exec i3 --shmlog-size=26214400
#exec plasma-i3.sh

#!/usr/bin/env bash
#xrdb -merge ~/.Xresources
# exec i3 --shmlog-size=26214400
#exec plasma-i3.sh
#exec i3
exec dbus-launch --sh-syntax --exit-with-session startplasma-x11
