#!/usr/bin/env bash
#?
# salt-apply - Run salt-call with customized options
#
# USAGE
#
#     salt-apply OPTIONS
#
# OPTIONS
#
#    -t    (Optional) Run states in test mode
#    -l    (Optional) Run state.apply with -l trace option
#
# BEHAVIOR
#
#    Runs salt-call in local mode with brief output enabled.
#
#?

# {{{1 Exit on any error
set -e

# {{{1 Configuration
post_args=()

# {{{1 Helpers
function die() {
    echo "Error: $@" >&2
    exit 1
}

# {{{1 Options
while getopts "tl" opt; do
    case "$opt" in
	t) post_args+=("test=True") ;;
	l) post_args+=("-l trace") ;;
	'?') die "Unknown option" ;;
    esac
done

# {{{1 Run
exec salt-call --local --state-output=changes state.apply ${post_args[@]}
