#!/usr/bin/env bash
#?
# salt-apply - Run salt-call with customized options
#
# USAGE
#
#     salt-apply OPTIONS
#
# OPTIONS
#
#    -t           Run states in test mode
#    -l           Run state.apply with -l trace option
#    -s STATE     State to run, can only be provided once
#    -p PILLAR    Set pillar values, can only be provided once
#
# BEHAVIOR
#
#    Runs salt-call in local mode with brief output enabled.
#
#?

# {{{1 Exit on any error
set -e

# {{{1 Configuration
post_args=()
state=""

# {{{1 Helpers
function die() {
    echo "Error: $@" >&2
    exit 1
}

# {{{1 Options
while getopts "tls:p:" opt; do
    case "$opt" in
	t) post_args+=("test=True") ;;
	l) post_args+=("-l trace") ;;
	s) state="$OPTARG" ;;
	p) post_args+=("pillar='$OPTARG'") ;;
	'?') die "Unknown option" ;;
    esac
done

# {{{1 Run
exec salt-call --local --state-output=changes state.apply "$state" ${post_args[@]}
