#!/bin/sh
#
# Kernel post-install hook for dracut.
#
# Arguments passed to this script: $1 pkgname, $2 version.
#

# Configuration
out_file="{{ pillar.initramfs.initramfs_file_xbps_relpath }}"

# Arguments
PKGNAME="$1"
VERSION="$2"

# Check for dracut
if [ ! -x bin/dracut ]; then
        exit 0
fi

# Build initramfs
dracut -q --force "$out_file" ${VERSION}
exit $?
