#!/bin/sh
#
# Kernel post-install hook for dracut.
#
# Arguments passed to this script: $1 pkgname, $2 version.
#

# {{{1 Configuration
out_file="boot/efi/void-initramfs.img"

# {{{1 Arguments
PKGNAME="$1"
VERSION="$2"

# {{{1 Check for dracut
if [ ! -x bin/dracut ]; then
        exit 0
fi

# {{{1 Build initramfs
dracut -q --force "$out_file" ${VERSION}
exit $?
