#!/usr/bin/env bash
#?
# discord - Run Discord via flatpak
#
# USAGE
#
#     discord
#
# BEHAVIOR
#
#     Start Discord flatpak app.
#
#?

# Exit on any error
set -e

# Run
exec flatpak run {{ pillar.discord.flatpak_app }}
